### ISSUE TITLE
polyPerimeter doesn't mention units

### ISSUE THREAD

**Issue by RussellGrayxd** [jeffreyevans/spatialEco#16]
The function seems to work fine, I just have no idea what the units are that it is outputting to. My polygon output is in Km.sq. 

An update on the help file would be perfect.

Best,

RG

**Comment by jeffreyevans** [comment]
Russell,
The units would be the same as the planar or projection units.  This would never be a unit squared because it reflects the distance units of the geographic space. I will add a sentence in the help document reflecting unit output. Check your projection to see what units your are in ie., sp::proj4string(x)

Best,
Jeff


Jeffrey S. Evans, Ph.D., (He, Him)

Senior Landscape Ecologist & Biometrician

The Nature Conservancy | Global Lands Science

Visiting Professor | University of Wyoming | Ecosystem Sciences

Office, Agriculture - C6, Laramie, WY  82070

jeffrey_evans@tnc.org<mailto:jeffrey_evans@tnc.org> | (970) 672-6766<tel:(970)%20672-6766>
https://www.nature.org/en-us/about-us/who-we-are/our-people/jeff-evans/

**Comment by RussellGrayxd** [comment]
Thanks for such a quick reply Jeffrey,
I figured that would be the case, but for some reason the output numbers don't seem to make much sense. It could very well be something I'm doing wrong on my end.
for example:
all of my polygons have an output of km.sq, and the total area comes out as about 350, when I use the polyPerimeter function the perimeter output reads 0.07143, then for others, the output (with the same km.sq output and similar sized area) outputs as 56,859. 
If the function is written to use the same output units as the polygon, then there must be something wrong with my code, so I'll go take a look at it and try again. 

Thanks again for the speedy reply! Have a great day!

-Russell Gray
    On Tuesday, September 17, 2019, 11:54:34 p.m. GMT+7, Jeffrey S. Evans <notifications@github.com> wrote:  
 
 
Closed #16.
