### ISSUE TITLE
all raster commands are showing error in spatialEco package

### ISSUE THREAD

**Issue by ranaranjeet92** [jeffreyevans/spatialEco#17]
I am not able to run data smoothing command : smooth.time.series(raster_stack),  sg.smooth() and few others.  It is showing error: 
Error in .overlayList(x, fun = fun, filename = filename, forcefun = forcefun,  : 
  cannot use this formula, probably because it is not vectorized

Please help. I tried to run the command with raster stack and brick both but non are working. And I tried package installation from gitHub and CRAN both. Still same error.

**Comment by jeffreyevans** [comment]
I do need additional information to address this issue, perhaps some example data that is failing. That said, I have been having serious issues with raster::calc and raster::overlay erroneously failing functions that are passed to them, even with specifically vectorized output of fixed length and with functions that have previously worked. I have been waiting to really address this issue until the development of the terra package is out of beta and up on CRAN so I can take advantage of moving some of the underlying data reading and swapping to Rcpp.

I would point out that not “all raster commands are showing error”. There are numerous functions associated with raster analysis in the spatialEco package and you are only having issue with one. The sg.smooth function does not accept a raster directly and operates on a vector. However, the “Error in .overlayList” is a reoccurring problem in these two raster functions and is associated with a couple of functions in spatialEco. This error is generated internally upon a periodic function check so, there is no way to pass it without a fail of the function. A warning action would be appreciated.

If you have available RAM, an alternative would be to coerce your data to an sp class object. I intentionally structed some of these functions so that they can be applied to something other than a raster stack/brick object and will update the applicable function documentation accordingly.

Add libraries

library(raster)
library(spatialEco)

He we create a 50x50x10 stack of random data to test on

create.random.stack <- function(i=50, j=50, k=10, min=0, max=1){
  do.call(stack, replicate(k, raster(matrix(runif(i*j, min, max),i,j))))
}
r <- create.random.stack()

Then test the functions.

( r.smooth <- smooth.time.series(r, f = 0.2, smooth.data = TRUE) )
( r.sg <- calc(r, sg.smooth) )

Alternately we can coerce to sp class object and operate on the data.frame in the @data slot.

r.sp <- as(r, "SpatialPixelsDataFrame")

Let’s first duplicate the object then use apply to iterate over the array with the sg.smooth function. Note; you have to transpose the resulting matrix and can then just replace @data with the results with a pipe, which is why we create a new object.

r.sg <- r.sp
r.sg@data <- as.data.frame(t(apply(r.sp@data, MARGIN=1, FUN=sg.smooth)))

We can pass an sp object directly to the smooth.time.series function this returns a data.frame that can be piped into the @data slot

r.smooth <- r.sp
r.smooth@data <- smooth.time.series(r.sp, f = 0.2, smooth.data = TRUE)

You can then coerce back to a raster stack object

r.sg <- stack(r.sg)
r.smooth <- stack(r.smooth)

I hope this helps.

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist / Biometrician
The Nature Conservancy | Global Lands Science
Visiting Professor | University of Wyoming | Zoology & Physology
Laramie, WY | jeffrey_evans@tnc.org<mailto:jeffrey_evans@tnc.org> | (970) 672-6766<tel:(970)%20672-6766>

**Comment by ranaranjeet92** [comment]
Sir thank you for your response. I tried with your given code and that is working for manual stack data. But for actual raster still same problem. I am attaching some sample raster files. the errors for smoothing raster stack are as follows.


code used:library("raster")library("spatialEco")setwd(":/")list <- list.files( , pattern = "*.tif$")listraster_stack = stack(list)      #raster stack using raster packager<- raster_stack
raster_stack.smooth<-smooth.time.series(r, f=0.2, smooth.data = FALSE)r.smooth <- sg.smooth(r)

console:
> raster_stack.smooth<-smooth.time.series(r, f=0.2, smooth.data = FALSE)Error in .overlayList(x, fun = fun, filename = filename, forcefun = forcefun,  :   cannot use this formula, probably because it is not vectorized
> r.smooth <- sg.smooth(r)Error in which(is.na(x)) : argument to 'which' is not logical


Thanking You,
Ranjeet SinghPhD candidateClimate Change and Forest Influence DisciplineForest Ecology and Climate Change Division
Forest Research InstituteDehradun, India 

    On Wednesday, 25 September, 2019, 11:01:18 pm IST, Jeffrey S. Evans <notifications@github.com> wrote:  
 
 I do need additional information to address this issue, perhaps some example data that is failing. That said, I have been having serious issues with raster::calc and raster::overlay erroneously failing functions that are passed to them, even with specifically vectorized output of fixed length and with functions that have previously worked. I have been waiting to really address this issue until the development of the terra package is out of beta and up on CRAN so I can take advantage of moving some of the underlying data reading and swapping to Rcpp.

I would point out that not “all raster commands are showing error”. There are numerous functions associated with raster analysis in the spatialEco package and you are only having issue with one. The sg.smooth function does not accept a raster directly and operates on a vector. However, the “Error in .overlayList” is a reoccurring problem in these two raster functions and is associated with a couple of functions in spatialEco. This error is generated internally upon a periodic function check so, there is no way to pass it without a fail of the function. A warning action would be appreciated.

If you have available RAM, an alternative would be to coerce your data to an sp class object. I intentionally structed some of these functions so that they can be applied to something other than a raster stack/brick object and will update the applicable function documentation accordingly.

Add libraries

library(raster)
library(spatialEco)

He we create a 50x50x10 stack of random data to test on

create.random.stack <- function(i=50, j=50, k=10, min=0, max=1){
 do.call(stack, replicate(k, raster(matrix(runif(i*j, min, max),i,j))))
}
r <- create.random.stack()

Then test the functions.

( r.smooth <- smooth.time.series(r, f = 0.2, smooth.data = TRUE) )
( r.sg <- calc(r, sg.smooth) )

Alternately we can coerce to sp class object and operate on the data.frame in the @data slot.

r.sp <- as(r, "SpatialPixelsDataFrame")

Let’s first duplicate the object then use apply to iterate over the array with the sg.smooth function. Note; you have to transpose the resulting matrix and can then just replace @data with the results with a pipe, which is why we create a new object.

r.sg <- r.sp
r.sg@data <- as.data.frame(t(apply(r.sp@data, MARGIN=1, FUN=sg.smooth)))

We can pass an sp object directly to the smooth.time.series function this returns a data.frame that can be piped into the @data slot

r.smooth <- r.sp
r.smooth@data <- smooth.time.series(r.sp, f = 0.2, smooth.data = TRUE)

You can then coerce back to a raster stack object

r.sg <- stack(r.sg)
r.smooth <- stack(r.smooth)

I hope this helps.

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist / Biometrician
The Nature Conservancy | Global Lands Science
Visiting Professor | University of Wyoming | Zoology & Physology
Laramie, WY | jeffrey_evans@tnc.org<mailto:jeffrey_evans@tnc.org> | (970) 672-6766<tel:(970)%20672-6766>

**Comment by jeffreyevans** [comment]
Please read my previous response carefully. As stated, you cannot pass a raster class object directly to the spatialEco::sg.smooth, it accepts a vector as input. Since, in the example code that I provide, I cannot reproduce your bug, it is difficult for me to address it. The raster.smooth function has previous worked without issue but, somewhere in a recent release of raster it has started throwing this error on certain data. I have error checking in the function that should prevent any type of catch error in calc or overlay but, this does not seem to matter. The error seems quite erroneous so, I cannot account for it in my function. This is why I provided you a workaround with an sp approach.

Please also note that you cannot send attachments through the GitHub response system. Please put them up on a public repository or email me directly.

-Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist / Biometrician
The Nature Conservancy | Global Lands Science
Visiting Professor | University of Wyoming | Zoology & Physology
Laramie, WY | jeffrey_evans@tnc.org<mailto:jeffrey_evans@tnc.org> | (970) 672-6766<tel:(970)%20672-6766>
