### ISSUE TITLE
Include sf and rgdal as dependency

### ISSUE THREAD

**Issue by ledwindra** [jeffreyevans/spatialEco#26]
Hi @jeffreyevans 

Thank you for making this package, really helpful. I'm currently using it for calculating VRM. But there's a minor issue that you may want to address. 

1. Include `sf` when installing this package so that other users don't have to install it manually if that's possible
```R
> library(raster)
Loading required package: sp
> library(spatialEco)
Error: package or namespace load failed for ‘spatialEco’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘sf’
```

2. Include `rgdal` when installing this package so that other users don't have to install it manually if that's possible
```R
> data(elev)
> elev <- projectRaster(elev, crs="+proj=robin +datum=WGS84",res=1000, method='bilinear')
Error in .requireRgdal() : package 'rgdal' is not available
```

Because in this case I need to calculate `vrm` which needs elev as an example. This works out after all, but automatically installing the dependency may help other users perhaps.

Thanks once again :)

**Comment by jeffreyevans** [comment]
Well, both sf (directly) and rgdal (proxy) are package dependencies and are, in fact, installed with the package. That they are not available tells me one of two things: 1) you are using a Mac, which has well know problems with spatial packages and needs special attention to install sf, rgdal and rgeos before any packages that may need them or; 2) for some reason the packages are just not installing on your system, which is something that you need to troubleshoot. I imagine that you are also missing rgeos. This has nothing to do with the spatialEco package as dependencies are installed through the install.packages function.
Admittedly, there have recently been some quirks with R installing dependencies but, it is difficult to isolate exactly what is going on and is not due to package errors, which would be caught during the CRAN check. Sometimes it has to do with only the source being available on the repository and the end user not having RTools installed to compile from source or the source just failed (as happened to me just yesterday with three package updates). The source hits the repositories before the binaries, sometimes weeks before and if you do not have your preferences set to ignore package sources, they will try to install.

I would note that CRAN has fairly clear guidelines on when a developer should require an imported dependency verses a suggested package. A suggested package, unless specified in the dependencies argument, is not automatically installed. Package functions that require “one off” packages are written to look to see if the package exists and if not returns a message that it does not exist and should be installed (which is different from what you are getting).

So, everything that you are getting at is actually delt with in CRAN package guidance, and rigorous code checks on submission. You can ensure that you get all related packages by using the argument: `dependencies =c("Depends", "Imports", "LinkingTo", "Suggests", "Enhances")` in the `install.packages` function.

If you look at the DESCRIPTION file associated with a package the “imports” field will tell you what the package imports (requires install with package). It is also detailed on the packages CRAN website<https://cran.r-project.org/web/packages/spatialEco/index.html>. Since rgdal is a hard and fast dependency for a few of my dependences (raster, sp, spdep, sf), it is redundant to specify in the spatialEco dependencies and, I actually do not use any rgdal package calls directly; raster::projectRaster is not one of mine but, does use rgdal::spTransform. Any calls to rgdal are coming from an associated imported package.

-Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist & Biometrician
The Nature Conservancy | Protected Lands Science
Visiting Professor | University of Wyoming | Zoology & Physiology
Laramie, WY | ***@***.******@***.***> | (970) 672-6766<tel:(970)%20672-6766>

From: Lukman Edwindra ***@***.***>
Sent: Thursday, April 15, 2021 10:52 PM
To: jeffreyevans/spatialEco ***@***.***>
Cc: Jeffrey Evans <jeffrey_evans@TNC.ORG>; Mention ***@***.***>
Subject: [jeffreyevans/spatialEco] Include sf and rgdal as dependency (#26)


Hi @jeffreyevans<https://github.com/jeffreyevans>

Thank you for making this package, really helpful. I'm currently using it for calculating VRM. But there's a minor issue that you may want to address.

  1.  Include sf when installing this package so that other users don't have to install it manually if that's possible

> library(raster)



Loading required package: sp



> library(spatialEco)



Error: package or namespace load failed for ‘spatialEco’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):



 there is no package called ‘sf’

  1.  Include rgdal when installing this package so that other users don't have to install it manually if that's possible

> data(elev)



> elev <- projectRaster(elev, crs="+proj=robin +datum=WGS84",res=1000, method='bilinear')



Error in .requireRgdal() : package 'rgdal' is not available

Because in this case I need to calculate vrm which needs elev as an example. This works out after all, but automatically installing the dependency may help other users perhaps.

Thanks once again :)

**Comment by ledwindra** [comment]
Hi @jeffreyevans 

Thanks for replying. Well noted, it's case close then. I was just wondering if it's possible to do but it looks like that's not necessary either. Yes I'm using a Mac and only 2 of those packages that are not included. I apologize for the submitting this issue.

Best regards,
Lukman
