### ISSUE TITLE
rasterCorrelation producing rings in output raster

### ISSUE THREAD

**Issue by umar12** [jeffreyevans/spatialEco#30]
I am reading in two .tif files as r1 and r2 using raster::raster("*.tif") and trying to do spatial correlation between the two by using the following command.
r.cor <- rasterCorrelation(r1, r2, s = 5, type = "pearson")
First, the program is extremely slow and takes about 20 minutes for a relatively small raster. Second, I am getting circular rings in my output raster. The example provided with the function do not produce any of such affect. 
![raster_correlation](https://user-images.githubusercontent.com/7946749/121638275-2179a680-caa4-11eb-8135-5eb8f68f6ff4.png)

**Comment by jeffreyevans** [comment]
Unfortunately, I cannot reproduce your issue(s) other than performance. If you can make the rasters available to me perhaps I can track down what is going on. I do not know what your definition of a “relatively small raster” is but, 20 minute runtimes seems to be quite excessive. Your output is also very odd given the by defining the argument s=5 would result in a 5x5 rectangular focal matrix and not circular. That said, there are some performance issues cropping up with the raster package due to development efforts being put elsewhere (ie., terra). In looking at your results, I am wondering if you have a combination of a previous circular function that was applied to the raster(s) along with zero covariance or NA’s influencing the resulting pattern.

The raster package, by default, does not remove NA’s so it there are any present in the focal matrix the results are written out as NA. Changing this makes is so that NA’s can be present, along with true values, and still result in a valid statistic.

I just pushed a version of the rasterCorrelation function, to the GitHub spatialEco development version, that supports the terra raster class which, will make the function quite a bit faster. I just benchmarked the function on a 5000 x 5000 random raster problem. The raster package benchmarked horrifically at “25 minutes” whereas, the terra package had a runtime of “23 seconds”. Please note that I changed default NA behavior to rm.na=TRUE so that outputs were consistent between packages.

If you are not familiar with terra, it is the replacement package for raster (same developer) and is written primarily in Rcpp thus, addressing many previous performance issues with raster. The object class is SpatRast (regardless of single or multiband rasters) and is created/read using the terra::rast function.

#********************************
library(raster)
library(terra)
library(spatialEco)

x = raster(ncol=5000, nrow=5000)
x[] <- runif(ncell(x), 0, 1)
y = x
y[] <- runif(ncell(x), 0, 1)

# Benchmark for raster class
system.time({
  r.cor <- rasterCorrelation(x, y, s = 5, type = "pearson")
})

# Benchmark for terra class
x <- rast(x)
y <- rast(y)
system.time({
  r.cor <- rasterCorrelation(x, y, s = 5, type = "pearson")
})
#********************************

Best,
Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist & Biometrician
The Nature Conservancy | Protected Lands Science
Visiting Professor | University of Wyoming | Zoology & Physiology
Laramie, WY | ***@***.******@***.***> | (970) 672-6766<tel:(970)%20672-6766>

From: Muhammad Umar ***@***.***>
Sent: Friday, June 11, 2021 12:03 AM
To: jeffreyevans/spatialEco ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffreyevans/spatialEco] rasterCorrelation producing rings in output raster (#30)


I am reading in two .tif files as r1 and r2 using raster::raster("*.tif") and trying to do spatial correlation between the two by using the following command.
r.cor <- rasterCorrelation(r1, r2, s = 5, type = "pearson")
First, the program is extremely slow and takes about 20 minutes for a relatively small raster. Second, I am getting circular rings in my output raster. The example provided with the function do not produce any of such affect.
[raster_correlation]<https://user-images.githubusercontent.com/7946749/121638275-2179a680-caa4-11eb-8135-5eb8f68f6ff4.png>

**Comment by umar12** [comment]
Thank you for your timely and very helpful response. MY raster is about 4000 * 3000 pixels with 30m cell size.
"_I am wondering if you have a combination of a previous circular function that was applied to the raster(s) along with zero covariance or NA’s influencing the resulting pattern_." Yes it is indeed the case. On of the input raster is an output from point density with circular window. I should have thought of that earlier.
I am glad to know the performance improvement as I intend to use the function quite a lot in the coming days. Thank you for all your efforts.
