### ISSUE TITLE
Incorporation of interaction effects in logistic.regression()

### ISSUE THREAD

**Issue by mcgregorian1** [jeffreyevans/spatialEco#51]
Hi, I am trying to fit a spatial binomial glm with interactions, but the arguments for the`logistic.regression()` function only allow to specify the columns and not provide a formula. I assumed that I could center my covariates and manually create columns representing the interaction (e.g. taking the product of them) before adding them in as separate covariates.

My question is, is this the correct way to incorporate interactions, given we can't specify a formula?

The final code looks like this:
```
## dt is the table with the centered covariates. 
## `dist` is a binary response

## non-spatial glm
# mod <- glm(dist ~ cov1 + cov2 + cov3 + cov4 + 
#              cov5*cov6 + cov5*cov7 + cov5*cov8 +
#              cov5*cov9, family = binomial(link = "logit"), data=dt)

spo <- st_as_sf(dt, coords=c("x", "y"), crs=4326)
dt[, `:=` (cov56 = cov5 * cov6,
              cov57 = cov5 * cov7,
              cov58 = cov5 * cov8,
              cov59 = cov5 * cov9)]
out <- logistic.regression(dt, y="dist", x=c("cov1", "cov2", "cov3",  "cov4", "cov5", "cov6",
                                                "cov7", "cov8", "cov9", "cov56", "cov57", 
                                                "cov58", "cov59"),
                           autologistic=TRUE, coords=st_coordinates(spo), longlat=TRUE)
```

**Comment by jeffreyevans** [comment]
Ian,
Unfortunately, you are correct, the only way to account for interaction(s) would be to derive a new column representing the interaction. The legacy of this function was that I wrote it for ESRI as a tool that leveraged their R-ArcGIS Bridge API and a column based model call is how it needed to be structured to interface with the ArcToolbox. A graduate student requested that it be made available as a function so, I did some modifications and included it in spatialEco. Recently, I changed the dependency of the autologistic spatial lag function to sf rather than sp but, have not done much otherwise.

I will take note of this and  add a formula interface to my to-do list. This package is in active development so, I will try to include this enhancement in the next release but, will likely not get to it for a few weeks. If you are in critical need please let me know and I will see what I can do.

Best,
Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist & Biometrician
The Nature Conservancy | Global Protect, Science
Visiting Professor | University of Wyoming | Zoology & Physiology
Laramie, WY | ***@***.******@***.***> | (970) 672-6766<tel:(970)%20672-6766>
ORCID-ID 0000-0002-5533-7044


From: Ian McGregor ***@***.***>
Sent: Thursday, January 26, 2023 7:02 AM
To: jeffreyevans/spatialEco ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffreyevans/spatialEco] Incorporation of interaction effects in logistic.regression() (Issue #51)


Hi, I am trying to fit a spatial binomial glm with interactions, but the arguments for thelogistic.regression() function only allow to specify the columns and not provide a formula. I assumed that I could center my covariates and manually create columns representing the interaction (e.g. taking the product of them) before adding them in as separate covariates.

My question is, is this the correct way to incorporate interactions, given we can't specify a formula?

The final code looks like this:

## dt is the table with the centered covariates.

## `dist` is a binary response



## non-spatial glm

# mod <- glm(dist ~ cov1 + cov2 + cov3 + cov4 +

#              cov5*cov6 + cov5*cov7 + cov5*cov8 +

#              cov5*cov9, family = binomial(link = "logit"), data=dt)



spo <- st_as_sf(dt, coords=c("x", "y"), crs=4326)

dt[, `:=` (cov56 = cov5 * cov6,

              cov57 = cov5 * cov7,

              cov58 = cov5 * cov8,

              cov59 = cov5 * cov9)]

out <- logistic.regression(dt, y="dist", x=c("cov1", "cov2", "cov3",  "cov4", "cov5", "cov6",

                                                "cov7", "cov8", "cov9", "cov56", "cov57",

                                                "cov58", "cov59"),

                           autologistic=TRUE, coords=st_coordinates(spo), longlat=TRUE)

**Comment by mcgregorian1** [comment]
Hi Jeff, sorry for the delay but thank you for your explanation! I am not in critical need for this, so no rush on getting this implemented; I was just checking on different methods for running spatial logistic regression.

**Comment by jeffreyevans** [comment]
I am adding a formula interface in the next version.
