### ISSUE TITLE
Error in breeding.density

### ISSUE THREAD

**Issue by ericnewkirk** [jeffreyevans/spatialEco#53]
When running breeding.density from the CRAN version I get the following error:

```
Error in Ops.units(di, bw) : 
  both operands of the expression should be "units" objects
```

I believe this is due to changes in the class of the object returned by `sf::st_distance` (sf version 1.0-9). I resolved it for now by changing the `point.density` function defined within `breeding.density` as follows:

```r 
point.density <- function(x, bw, self = TRUE) {
    d <- sf::st_distance(x, x)
    d <- matrix(as.numeric(d), nrow(d), ncol(d))
```

I can submit a pull request if you'd like, but I'm not sure this is actually the best solution. I installed from github and get the same error.

**Comment by jeffreyevans** [comment]
Eric,
Yes, you are correct, it appears that sf is outputting a different distance matrix format. I have wanted to change to a different (faster) distance matrix function but, the advantage of sf is that it will return spheroid distances so, lat/long is a valid input. I will patch this shortly. I believe that the underlying issue is that the function is now returning a units class object. As such, I should be able to simply use: `units:: drop_units(sf::st_distance(x, x))` which is functionally what you are doing by coercing the matrix to numeric but simply drops the class. An advantage of having a units object is that I can easily change units so that the function is always using the same unit of measure, regardless of projection. So, in the case of spheroid distances returning kilometers, on the fly, can define output as meters. May mull over exactly how I want to handle this. Anyway, thank you for pointing this out.

Best,
Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist & Biometrician
The Nature Conservancy | Global Protect, Science
Visiting Professor | University of Wyoming | Ecosystem Sciences
Laramie, WY | ***@***.******@***.***> | (970) 672-6766<tel:(970)%20672-6766>
ORCID-ID 0000-0002-5533-7044
TNC Biography<https://www.nature.org/en-us/about-us/who-we-are/our-people/jeff-evans/> – Google Scholar<https://scholar.google.com/citations?user=FwU_ppgAAAAJ&hl=en>

From: Eric Newkirk ***@***.***>
Sent: Wednesday, February 22, 2023 3:09 PM
To: jeffreyevans/spatialEco ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffreyevans/spatialEco] Error in breeding.density (Issue #53)


When running breeding.density from the CRAN version I get the following error:

Error in Ops.units(di, bw) :

  both operands of the expression should be "units" objects

I believe this is due to changes in the class of the object returned by sf::st_distance (sf version 1.0-9). I resolved it for now by changing the point.density function defined within breeding.density as follows:

point.density <- function(x, bw, self = TRUE) {

    d <- sf::st_distance(x, x)

    d <- matrix(as.numeric(d), nrow(d), ncol(d))

I can submit a pull request if you'd like, but I'm not sure this is actually the best solution. I installed from github and get the same error.

**Comment by jeffreyevans** [comment]
Eric,
I have tried several different things and I cannot reproduce your error. Could you please send me your session information, an str of your data and what your code looks like? It would really help me troubleshoot things. The “units” error reference has me scratching my head as it indicates something very specific regarding object classes coming from sf. In the current version of sf (1.0-9) the st_distance function, with the way I am calling it, returns a dense matrix and not a units object. I am wondering if it is behaving differently based on the sf input (eg., an sf/tribble class object). I do not necessarily want to force a coercion if there is another way to deal with multiple input/output types.

Best,
Jeff

From: Eric Newkirk ***@***.***>
Sent: Wednesday, February 22, 2023 3:09 PM
To: jeffreyevans/spatialEco ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffreyevans/spatialEco] Error in breeding.density (Issue #53)


When running breeding.density from the CRAN version I get the following error:

Error in Ops.units(di, bw) :

  both operands of the expression should be "units" objects

I believe this is due to changes in the class of the object returned by sf::st_distance (sf version 1.0-9). I resolved it for now by changing the point.density function defined within breeding.density as follows:

point.density <- function(x, bw, self = TRUE) {

    d <- sf::st_distance(x, x)

    d <- matrix(as.numeric(d), nrow(d), ncol(d))

I can submit a pull request if you'd like, but I'm not sure this is actually the best solution. I installed from github and get the same error.

**Comment by jeffreyevans** [comment]
Never mind, I figured it out, it is related to unit class output from st_distance. In the help under value (outputs) it states; “If the coordinate reference system of x was set, these functions return values with unit of measurement”. So, if the projection is defined then the result is a units class object. Here is the fix, I will push it to GitHub and R-Universe shortly.

d <- sf::st_distance(x, x)
                if(inherits(d, "units"))
                  d <- units::drop_units(d)

Best,
Jeff

From: Eric Newkirk ***@***.***>
Sent: Wednesday, February 22, 2023 3:09 PM
To: jeffreyevans/spatialEco ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffreyevans/spatialEco] Error in breeding.density (Issue #53)


When running breeding.density from the CRAN version I get the following error:

Error in Ops.units(di, bw) :

  both operands of the expression should be "units" objects

I believe this is due to changes in the class of the object returned by sf::st_distance (sf version 1.0-9). I resolved it for now by changing the point.density function defined within breeding.density as follows:

point.density <- function(x, bw, self = TRUE) {

    d <- sf::st_distance(x, x)

    d <- matrix(as.numeric(d), nrow(d), ncol(d))

I can submit a pull request if you'd like, but I'm not sure this is actually the best solution. I installed from github and get the same error.

**Comment by ericnewkirk** [comment]
Sorry, I missed your follow-up message. I was about to send a script that I think would've looked _very_ familiar to you. Dropping the units if present should definitely take care of it. FWIW I agree with the preference for actual geographic distance rather than approximating with trig, even if it means sacrificing a bit of performance.

Thanks!
