### ISSUE TITLE
convexHull causing session crash for some point samples

### ISSUE THREAD

**Issue by victorcazalis** [jeffreyevans/spatialEco#60]
I am using convexHull regularly. Most of the time it works super well and from time to time, it crashes the session (using spatialEco v2.0.2). It happened today so I've tried to locate the problem testing many different values of alpha and the problem was always the same. I thus believe it's coming from the data I use. I've attached a shp including the points I use and you can likely replicate the error just using these two lines:

`dat<-st_read("Example_alpha_crash.shp");
hull<-spatialEco:::convexHull(dat, alpha = 250000)`

Note that I've removed duplicate points before using `dplyr::distinct(dat, as.character(geometry), .keep_all=T)`

It would be nice if the problem could be fixed or, at least, if the function could return an error message rather than leading to a session crash. Unless it's a problem from my side (which we'll see if you cannot replicate the error)...
[Example_alpha_crash.zip](https://github.com/jeffreyevans/spatialEco/files/12281093/Example_alpha_crash.zip)

**Comment by victorcazalis** [comment]
Hi,

I've been trying to find where the problem is coming from and it seems to be caused by points that are too close to each others. If I remove points that are distant by less than 100m, the function is not crashing anymore (for some point sets 10m was sufficient, for others 100m was needed). 
`dat<-st_read("Example_alpha_crash.shp")
Coords_simplif<-st_coordinates(dat) %>% base::round(., digits=-2)
dat$Coord_simplif<-paste(Coords_simplif[,1], Coords_simplif[,2], sep=":")
dat_subsample<-dplyr::distinct(dat, Coord_simplif, .keep_all=T) 
hull<-spatialEco:::convexHull(dat_subsample, alpha = 25000000)`

I don't know exactly what is causing this issue but it might still be good to fix it, or to add this subsampling step within the convexHull function (or at least to mention that in the help of the function) to help future users. 
I'd be interested to know if you identify the cause of the crash, and to know if subsampling points distant by <100m will fix it for all sets of points or if sometimes this should be a higher threshold.

**Comment by jeffreyevans** [comment]
Unfortunately, there is no way for me to catch an error that causes a session crash. The function that is deriving the hull geometry is `alphahull::ashape` which is what is causing the crash. I have tried to catch the error but, it is happening in C++ and not R per se. As such, there is no way for me to head off the inevitable R session snafu. 

I am also not sure as to the nature of the crash. I have tried intensifying boundary data and have not been able to recreate the error/crash. I did get the session to crash once with your data but, there is not way to catch the error that caused it as, the R session is no longer active. I have looked into this and there is just nothing I can do and, since it seems data specific and sporadic, I cannot come up with criteria, on the spatial object side that would mitigate the issue. It does look like the [alphahull ](https://github.com/beatrizpateiro/alphahull) package is still being maintained (after a long period of inactivity) so, I will drop the author(s) a message to see what they think. They may be able to mitigate the crash on the C++ side. 
 
Please do note that, due to licensing constraints, this function is not included in the CRAN distribution, only in the development version. I am exploring some other methodologies for elastic convex hulls that would allow me to provide this function in the CRAN distribution. 

Best,
Jeff

Jeffrey S. Evans, Ph.D., | Senior Landscape Ecologist & Biometrician 
The Nature Conservancy | Global Protect, Science 
Laramie, WY | [jeffrey_evans@tnc.org](mailto:jeffrey_evans@tnc.org) 
ORCID-ID 0000-0002-5533-7044

**Comment by jeffreyevans** [comment]
I will monitor this in the development version.
