### ISSUE TITLE
Error when using the aspline.downscale's grid.search parameter

### ISSUE THREAD

**Issue by nikosGeography** [jeffreyevans/spatialEco#62]
I am using the package's example to downscale the image using the `aspline.downscale()`  function. When setting the `grid.search = TRUE` I am getting the following error:

`Error in h(simpleError(msg, call)):  error in evaluating the argument 'object' in selecting a method for function 'predict': recursive indexing failed at level 2`.

The code:

```
library(spatialEco)

if (require(geodata, quietly = TRUE)) {
  library(terra)
  library(geodata)
  
  # Download example data (requires geodata package)
  elev <- elevation_30s(country="SWZ",  path=tempdir())
  slp <- terrain(elev, v="slope")
  x <- c(elev,slp)
  names(x) <- c("elev","slope")
  tmax <- worldclim_country(country="SWZ", var="tmax", 
                            path=tempdir())
  tmax <- crop(tmax[[1]], ext(elev))
  names(tmax) <- "tmax"
  
  tmax.ds <- aspline.downscale(x, tmax, add.coords=TRUE, keep.model=TRUE, grid.search = TRUE)
```

The same error when using my actual dataset. Why that error when setting the `grid.search = TRUE`?

R 4.3.3, RStudio 2023.12.1 Build 402, Windows 11.

**Comment by jeffreyevans** [comment]
Nikolaos,
Thank you for alerting me to this bug, turned out to be a simple fix and was caused by a small change in the resulting caret object.

Best,
Jeff

From: Nikolaos Tziokas ***@***.***>
Sent: Thursday, March 28, 2024 6:32 AM
To: jeffreyevans/spatialEco ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffreyevans/spatialEco] Error when using the aspline.downscale's grid.search parameter (Issue #62)


I am using the package's example to downscale the image using the aspline.downscale() function. When setting the grid.search = TRUE I am getting the following error:

Error in h(simpleError(msg, call)): error in evaluating the argument 'object' in selecting a method for function 'predict': recursive indexing failed at level 2.

The code:

library(spatialEco)



if (require(geodata, quietly = TRUE)) {

  library(terra)

  library(geodata)



  # Download example data (requires geodata package)

  elev <- elevation_30s(country="SWZ",  path=tempdir())

  slp <- terrain(elev, v="slope")

  x <- c(elev,slp)

  names(x) <- c("elev","slope")

  tmax <- worldclim_country(country="SWZ", var="tmax",

                            path=tempdir())

  tmax <- crop(tmax[[1]], ext(elev))

  names(tmax) <- "tmax"



  tmax.ds <- aspline.downscale(x, tmax, add.coords=TRUE, keep.model=TRUE, grid.search = TRUE)

The same error when using my actual dataset. Why that error when setting the grid.search = TRUE?

R 4.3.3, RStudio 2023.12.1 Build 402, Windows 11.

**Comment by nikosGeography** [comment]
Thank you for your response. I just re-tried the code and I got the same error. Should I wait for an update of the spatialEco package?

**Comment by jeffreyevans** [comment]
Are you trying to install from CRAN, GitHub or R-Universe?

For R-Universe, you can use

install.packages('spatialEco', repos = c('https://jeffreyevans.r-universe.dev', 'https://cloud.r-project.org'))

And, for GitHub

remotes::install_github("jeffreyevans/spatialEco", force = TRUE)

It will be a few weeks before a new version is up on CRAN.

Best,
Jeff

**Comment by nikosGeography** [comment]
Problem solved my installing the package from the R-Universe.
